web:
  build: .
  command: sh -c "npm install; npm run start"
  ports:
    - "3000:3000"
  volumes:
    - /home/iglesiasfacu/BBDDNSQL/api-prueba/api:/api
  links:
    - "db:redis"
db:
  image: redis
  ports:
    - "6379:6379"
